unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

# List of plugins

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

#set -g default-terminal "screen-256color"
set -g base-index 1
setw -g pane-base-index 1

bind-key X kill-pane
bind | split-window -v -b -f

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features ",xterm-256color:RGB"

set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left

# Status bar background / foreground
set -g status-style "bg=#282c34,fg=#a0a8b7"
set -g status-left-length 40
set -g status-left "\
#[bg=#282c34,fg=#bf68d9][#h] \
#[bg=#282c34,fg=#4fa6ed][#S]\
#[bg=#282c34,fg=#a0a8b7]#{?client_prefix,#[fg=#e2b86b]:,}#[bg=#282c34,fg=#535965]\
"
set -g status-right-length 80
set -g status-right "#[bg=#282c34,fg=#8ebd6b][%a %d %b]#[bg=#282c34,fg=#a0a8b7] [%H:%M:%S] "
set -g status-bg "#282c34"
set -g window-status-separator ""
# Inactive window
set -g window-status-format "#[bg=#282c34,fg=#a0a8b7] #I #W "
# Active window
set -g window-status-current-format "#[bg=#282c34,fg=#8ebd6b] #I #W "
set -g pane-border-style "fg=#535965"
set -g pane-active-border-style "fg=#4fa6ed"
set -g message-style "bg=#e2b86b,fg=#282c34"
set -g message-command-style "bg=#282c34,fg=#e2b86b"
set -g mode-style "bg=#323641,fg=#e2b86b"
set -g clock-mode-colour "#4fa6ed"
set -g clock-mode-style 24

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g set-titles on
set -g set-titles-string "#S · #W"
set-option -g default-command 'tput cup "$(tput lines)"; exec "$SHELL" -l'
